algoritmo "crescente"
// Função :
// Autor :
// Data : 17/08/2023
// Seção de Declarações 
var

   n1, n2 : inteiro

inicio

   escreval("Digite dois numeros: ")
   leia(n1)
   leia(n2)
   
   enquanto n1 <> n2 faca
   
     se n1 > n2 entao
     escreval("Decrescente!")
     senao
     
     escreval("Crescente!")
     fimse
     
     escreval("Digite outros dois numeros:  ")
     leia(n1)
     leia(n2)
   fimenquanto

fimalgoritmo
